#include <windows.h>
#include <stdio.h>
#include <cstdio>
#include <iostream>
#include <string>
#include <fstream>
#include <Psapi.h>
#include <Tlhelp32.h>
#include <sddl.h>
#include <cstdint>
#include <winreg.h>
#include <initguid.h>
#include <GPEdit.h>